#!/bin/sh
cd `dirname $0` > /dev/null
SCRIPTPATH=`pwd -P`
cd - > /dev/null

if [ `getconf LONG_BIT` = "64" ]
then
    PERSONAL_QT_LIB_PATH=~/Qt/5.3/gcc_64/lib
else
    PERSONAL_QT_LIB_PATH=~/Qt/5.3/gcc/lib
fi

export LD_LIBRARY_PATH="$PERSONAL_QT_LIB_PATH"

"$SCRIPTPATH"/notepadqq "$@"
