#!/bin/sh

# Perform git clang-format on the necessary files
echo "========== Formatting =========="
git clang-format --style file --extensions 'cpp,h'
echo "============= Done ============="

# Only add the files that have been previously staged for commit
echo "==== Adding files to commit ===="
for f in $(git commit --short | awk '/^[AM]/{print $2}');do
    git add -v "$f"
done
echo "============= Done ============="
