######################################################################
# Automatically generated by qmake (3.0) mar set 6 19:25:17 2016
######################################################################

QT += testlib
QT += core gui svg widgets webkitwidgets printsupport network
CONFIG += c++11
TEMPLATE = app
TARGET = ui-tests
INCLUDEPATH += ../ui/

# Input
SOURCES += tst_notepadqqtest.cpp
