name: notepadqq 
version: '2.0.0-beta+git'
summary: A Notepad++-like editor for Linux.
description: |
  It helps developers by providing all you can expect from a general purpose text editor, such as syntax highlighting for more than 100 different languages, code folding, color schemes, file monitoring, multiple selection and much more.
  You can search text using the power of regular expressions. You can organize documents side by side. You can use real-time highlighting to find near identifiers in no time.
grade: stable
confinement: classic
icon: support_files/icons/hicolor/scalable/apps/notepadqq.svg
base: core24

apps:
  notepadqq:
    command: usr/bin/notepadqq
    extensions: [kde-neon-6]
    environment:
      DISABLE_WAYLAND: "1"  # See https://github.com/notepadqq/notepadqq/issues/806
    desktop: usr/share/applications/notepadqq.desktop
#   plugs:  # Plugs are not needed for classic confinement
#     - browser-support
#     - desktop
#     - desktop-legacy
#     - gsettings
#     - home
#     - media-hub
#     - network-bind
#     - network-manager
#     - opengl
#     - optical-drive
#     - removable-media
#     - unity7
#     - x11

parts:
  notepadqq:
    source: .
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DNQQ_BUILD_SNAP=ON
      - -DNQQ_BUILD_TESTS=OFF
    build-packages:
      - pkg-config
      - libuchardet-dev
    stage-packages:
      - libnss3
      - libuchardet0
