name: notepadqq 
version: '1.4.8+git'
summary: A Notepad++-like editor for Linux.
description: |
  It helps developers by providing all you can expect from a general purpose text editor, such as syntax highlighting for more than 100 different languages, code folding, color schemes, file monitoring, multiple selection and much more.
  You can search text using the power of regular expressions. You can organize documents side by side. You can use real-time highlighting to find near identifiers in no time.
grade: stable
confinement: classic
icon: support_files/icons/hicolor/scalable/apps/notepadqq.svg


apps:
  notepadqq: 
    command: bin/desktop-launch $SNAP/usr/local/lib/notepadqq/notepadqq-bin
    desktop: usr/local/share/applications/notepadqq.desktop
#   plugs:  # Plugs are not needed for classic confinement
#     - browser-support
#     - desktop
#     - desktop-legacy
#     - gsettings
#     - home
#     - media-hub
#     - network-bind
#     - network-manager
#     - opengl
#     - optical-drive
#     - removable-media
#     - unity7
#     - x11

parts:
  fixicon:
    plugin: nil
    after: [my-part]
    override-build: |
      sed -i 's|Icon=notepadqq|Icon=/usr/local/share/icons/hicolor/scalable/apps/notepadqq\.svg|' $SNAPCRAFT_STAGE/usr/local/share/applications/notepadqq.desktop

  my-part:

    build-packages:

      - qtbase5-dev
      - qtwebengine5-dev
      - libqt5websockets5-dev
      - libqt5svg5-dev
      - qttools5-dev-tools
      
      
    stage-packages: 
      
      - adwaita-icon-theme-full
      - bamfdaemon
      - coreutils
      - desktop-file-utils
      - gnome-menus
      - gtk2-engines-pixbuf
      - hicolor-icon-theme
      - libatk-adaptor
      - libcanberra-gtk-module
      - libgail-common
      - libqt5svg5
      - libqt5webkit5
      - light-themes
      - man-db
      - mime-support
      - numix-gtk-theme
      - overlay-scrollbar-gtk2
      - packagekit-gtk3-module
      - qtbase5-dev 
      - unity-gtk-module-common
      - unity-schemas
      
    options:
        DEFINES+=BUILD_SNAP 

    source: . 
    after: [desktop-qt5] 
    plugin: qmake

    override-build: |
      sed -i '/.*QMAKE_RPATH=$/d' src/ui/ui.pro  # Hack for forcing the use of RPATH
      snapcraftctl build
