name: Build and Test CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:

  notepadqq-linux:
    runs-on: ubuntu-latest
    steps:   
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: false
        file: build.Dockerfile

  notepadqq-macos:
    runs-on: macos-latest
    steps:   
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install dependencies
      run: brew install qt@6 uchardet
    - name: Build
      run: ./configure && make
    - name: Test
      run: ./src/ui-tests/ui-tests.app/Contents/MacOS/ui-tests